version: "3.7"

services:
  ut4masterserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: UT4MasterServer
    image: ${DOCKER_REGISTRY-}ut4masterserver
    build:
      context: .
      dockerfile: UT4MasterServer/Dockerfile
    volumes:
      - ./logs:/app/Logs
    ports:
      - "5000:80"
    networks:
      - net
    depends_on:
      - mongo
  ut4masterserver-web:
    container_name: UT4MasterServer-Web
    image: ${DOCKER_REGISTRY-}ut4masterserver-web
    build:
      context: UT4MasterServer.Web
      dockerfile: .docker/Dockerfile
    ports:
      - "5001:8080"
    networks:
      - net
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devroot
      - MONGO_INITDB_ROOT_PASSWORD=devroot
      - MONGO_INITDB_DATABASE=project
    ports:
      - "27015:27015"
    volumes:
      - ./db:/data/db
    networks:
      - net
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=devroot
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=devroot
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
    depends_on:
      - mongo
    ports:
      - "8888:8081"
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
    external: false
